### ISSUE TITLE
[Question] Changing CPU, Memory, ... with the API in java

### ISSUE THREAD

**Issue by critix** [softlayer/softlayer-java#13]
Hello

This project has been very usefull for me but now I want to edit the CPU and memory of my virtual machines. I tried to change it with editObject but this is only to change hostname. I've seen in python examples that you have to give the price for more CPU's and use something like upgrade but I can't figure it out at all. Does someone have an example of how to edit the memory/cpu of a VM through the softlayer API client for java?

Kind regards

**Comment by cretz** [comment]
I am afraid this is not available through the regular editObject method. This is considered an upgrade and will have to go through the order system. I suggest asking this on the forum at https://forums.softlayer.com/forum/softlayer-developer-network. I will also check on the exact calls for the upgrades.

cc @underscorephil

**Comment by raulcabero** [comment]
Hello,

take a look to this example:

//
// Example to Upgrades a VSI
// The example will upgrade the ram in a VSI
//

package testJava.testjavaArtifact;

import java.util.List;
import com.softlayer.api.*;
import com.softlayer.api.service.Account;
import com.softlayer.api.service.virtual.Guest;
import com.softlayer.api.service.product.Order;
import com.softlayer.api.service.product.item.Price;
import com.softlayer.api.service.container.product.order.Property;
import com.softlayer.api.service.container.product.order.Receipt;
import com.softlayer.api.service.container.product.order.virtual.guest.Upgrade;;

public class Main {
	public static void main(String[] args) throws Exception {
		// Your SoftLayer API username and key.
		// Generate one at https://manage.softlayer.com/Administrative/apiKeychain
		String user = "set me";
		String apikey = "set me";
		
		// Looking for the VSI you wish to upgrade
		ApiClient client = new RestApiClient().withCredentials(user, apikey);
                // Your accountID
		Long id = new Long(XXXX);
		Guest guestToUpgrade = null;
		for (Guest guest : Account.service(client, id).getVirtualGuests()) {		    
		    if (guest.getHostname().equals("myVSI"))
		    {
		    	guestToUpgrade = guest; 
		    }
		}
		
		// Build a skeleton SoftLayer_Container_Product_Order_Virtual_Guest_Upgrade object
		// containing the upgrade you wish to place.
		Upgrade orderData = new Upgrade();
		List<Price> prices = orderData.getPrices();
		
		// Build a skeleton SoftLayer_Product_Item_Price objects
		// Every item in SoftLayer's product catalog is assigned an id. Use these ids
		// to tell the SoftLayer API which options you want in your new server
		// in this case we are adding two disk to our virtual server.
		// to get the list of prices and category codes available for the virtual server you can call the SoftLayer_Virtual_Guest::getUpgradeItemPrices method
		// for more reference see: http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/getUpgradeItemPrices
		int[] pricesId = {1645};
		for(int i=0; i < pricesId.length; i++){
			Price price = new Price();
			price.setId(new Long(pricesId[i]));
			prices.add(price);
		}
		
		orderData.getVirtualGuests().add(guestToUpgrade);
		System.out.println(guestToUpgrade.getId());
		
		// Build a skeleton SoftLayer_Container_Product_Order_Property objects
		// in this case the upgrade will be immediately
		Property note = new Property();
		note.setName("NOTE_GENERAL");
		note.setValue("adding disks");
		
		Property maintenace = new Property();
		note.setName("MAINTENANCE_WINDOW");
		note.setValue("2015-03-2T20:00:00+12:00");
		
		orderData.getProperties().add(note);
		orderData.getProperties().add(maintenace);
		
		
		// upgrading the virtual guest
	    // you can use verifyOrder method to test that your upgrade is fine
	    // when you are ready you can call the placeOrder method
	    // for more reference see:
	    // http://sldn.softlayer.com/reference/services/SoftLayer_Product_Order
	    // http://sldn.softlayer.com/reference/services/SoftLayer_Product_Order/verifyOrder
	    // http://sldn.softlayer.com/reference/services/SoftLayer_Product_Order/placeOrder
	    Receipt receipt = Order.service(client).placeOrder(orderData, false);
	    System.out.println(receipt.getOrderId());
		
	}
}

I hope it helps

Regards

**Comment by cretz** [comment]
@critix, does this answer your question? I am marking this issue as closed but feel free to respond or reopen (or communicate on the SLDN developer forums) if further information is needed.

**Comment by clydedcruz** [comment]
Hi Chad 
Thanks for your suggestions .I implemented my own http client ,and it works fine .
Thanks and regards 

Clyde D'Cruz

**Comment by GlennVanSchil** [comment]
Hi i'm a team member of the project where critix is on and this does answer our question. Thank you very much!
