### ISSUE TITLE
Will the DNS service be implemented ?

### ISSUE THREAD

**Issue by DanieleVistalli** [softlayer/softlayer-java#14]
Is there any plan to implement the DNS management API in the Java API.

It's currently missing and it would be useful to know the overall Java API coverage of the entire API.

**Comment by cretz** [comment]
The entire API should be present. What API service are you expecting to be present that is not present? http://sldn.softlayer.com/reference/services/SoftLayer_Dns_Domain for example is present at `com.softlayer.api.service.dns.Domain` (of course the service being available as the static method `service` off of there). You can get the domains via `com.softlayer.api.service.Account::getDomains`.

**Comment by DanieleVistalli** [comment]
Perfect, thanks for the quick response. I'm going to test it out.

I just discovered the project. I'm quite excited to finally get a Java Client. Thanks
