### ISSUE TITLE
Can you provide a sample for getting an invoice PDF ?

### ISSUE THREAD

**Issue by DanieleVistalli** [softlayer/softlayer-java#15]
Can you provide a sample about getting and saving to disk PDFs for SoftLayer invoices ? What's the process for normal invoicies.

Is anything different needed for "detailed" invoices ?

Thanks in advance.

**Comment by cretz** [comment]
These general questions are usually best for the [SLDN forums](https://forums.softlayer.com/forum/softlayer-developer-network). I will see if a team member can answer here as well...

**Comment by DanieleVistalli** [comment]
I'm going to bring my question to the forums, if you can get the answer here it's great.

**Comment by cretz** [comment]
While investigating this issue, we have found a bug in obtaining byte arrays (such as `Account::getNextInvoicePdf`). I have opened #16 to address this.

**Comment by cretz** [comment]
With #16 resolved, can you now access the invoice PDF's?

**Comment by cretz** [comment]
Closing issue as resolved. Feel free to reopen or update the [forum post](https://forums.softlayer.com/forum/softlayer-developer-network/general-discussion/83359-getting-invoice-pdfs-using-the-java-client-how) if there are still issues.
