### ISSUE TITLE
Byte arrays are not properly marshalled from base 64 strings

### ISSUE THREAD

**Issue by cretz** [softlayer/softlayer-java#16]

**Comment by cretz** [comment]
This has been resolved by PR #17. I'll leave this open until the next version bump, but the fix is available in master.

**Comment by DanieleVistalli** [comment]
Thanks, I'll try to build it myself, any plan to deliver it to maven central ?

**Comment by cretz** [comment]
I was gonna wait until other bugs came around...but I can go ahead and do it tomorrow as 0.2.2. I'll update when done.

**Comment by DanieleVistalli** [comment]
If you can do that we'll move on with our development. Stay assured we're going to use the library extensively and will report any issue we find.

**Comment by cretz** [comment]
Done: https://repo1.maven.org/maven2/com/softlayer/api/softlayer-api-client/0.2.2/
