### ISSUE TITLE
NFS order container does not extend Order

### ISSUE THREAD

**Issue by nbow** [softlayer/softlayer-java#20]
The
com.softlayer.api.service.container.product.order.network.performancestorage.Nfs
and
com.softlayer.api.service.container.product.order.network.performancestorage.Iscsi
objects do not extend Order, like the other Container objects. This prevents a verifyOrder, and presumably a placeOrder from running.

When passing the Nfs container to the order service's verifyOrder() the following error is thrown:
groovy.lang.MissingMethodException: No signature of method: com.sun.proxy.$Proxy171.verifyOrder() is applicable for argument types: (com.softlayer.api.service.container.product.order.network.performancestorage.Nfs) values: [com.softlayer.api.service.container.product.order.network.performancestorage.Nfs@22e04a44]
Possible solutions: verifyOrder(com.softlayer.api.service.container.product.Order)

**Comment by cretz** [comment]
Yes, we noticed this recently with the new code and are actively fixing it. It should be handled shortly, we have an internal bug on it. I will leave this open and respond here when that bug is resolved.

**Comment by cretz** [comment]
This should now be resolved if you regenerate the code. I will leave this open until the next release where I will release a generated version to maven central.

**Comment by camporter** [comment]
Released 0.2.3 which should address this issue.
