### ISSUE TITLE
[Question] Print price list ID is required

### ISSUE THREAD

**Issue by critix** [softlayer/softlayer-java#22]
I want to print a list of prices to get the right ID to create a subnet. I tried to look for a way to give my account ID through the ApiClient but this didn't need the ID. When I run the code it give me following error: 
Exception in thread "main" java.lang.IllegalStateException: ID is required to invoke public abstract java.util.List com.softlayer.api.service.product.item.Price$Service.getPackageReferences()
	at com.softlayer.api.RestApiClient$ServiceProxy.invokeService(RestApiClient.java:282)
	at com.softlayer.api.RestApiClient$ServiceProxy.invoke(RestApiClient.java:466)
	at com.sun.proxy.$Proxy8.getPackageReferences(Unknown Source)
	at applicatie.getPrices(applicatie.java:430)
	at applicatie.main(applicatie.java:78)

This is the code I use:

ApiClient client = new RestApiClient()
				.withCredentials("OUR USERNAME",
						"THE KEY");
getPrices(client,account);

	public static void getPrices(ApiClient client, Account account) {
		Price.Service servicePrices = Price.service(client);

		List<Prices> p = servicePrices.getPackageReferences();

		for (Prices price : p) {
			System.out.println(price.getId() + price.getItemPriceId());
		}
	}

Does anyone have the code to print a list of ID's and Names to find the subnet priceId. Or does someone have the code to create one.

**Comment by cretz** [comment]
In order to call that method, you must already have an ID on the price. There are other ways to get this pricing information. @raulcabero, can you provide API information for obtaining the prices? Also, in the future, the easiest forum for asking general API questions is via the SLDN forum at https://forums.softlayer.com/forum/softlayer-developer-network

**Comment by raulcabero** [comment]
Hello,

To get the list of prices you can call the following method http://sldn.softlayer.com/reference/services/SoftLayer_Product_Package/getItems to get the list o prices you only need to specify the correct package to get the list of packages use the following method http://sldn.softlayer.com/reference/services/SoftLayer_Account/getActivePackages here an example in java to get the list of prices of you want 

```java
package api.examples;

import com.google.gson.Gson;
import com.softlayer.api.ApiClient;
import com.softlayer.api.RestApiClient;
import com.softlayer.api.service.product.Package;

public class GetListPrices {

	public static void main(String[] args) {
		String user = "sl307608-rcabero";
		String apikey = "9f123905f8121d6862ea64630a3bb586f7900be12346deec1341d3e91e745528";
		
		// the VLAN id you wish to see its details
		Long packageId = new Long(0);

		// Declare the API client
		ApiClient client = new RestApiClient().withCredentials(user, apikey);
		Package.Service packageService = Package.service(client, packageId);
		
		try {
			Gson gson = new Gson();
			System.out.println(gson.toJson(packageService.getItemPrices()));

		} catch (Exception e) {
			System.out.println("Unable to retrieve the prices. "
					+ e.getMessage());
		}
	}

}
```

I hope it helps you

**Comment by critix** [comment]
Thank you, this works fine !

btw I received a mail with your softlayer credentials in the code. I suggest changing the credentials.
