### ISSUE TITLE
[Question] list transcoding jobs

### ISSUE THREAD

**Issue by riso** [softlayer/softlayer-java#27]
Hello,
I have an issue when reading transcoding jobs. The following code is what I am doing now

```
RestApiClient client = new RestApiClient().withCredentials("user", "key");
List<com.softlayer.api.service.network.media.transcode.Account> accounts =
    Account.service(client).getTranscodeAccounts();
List<Job> jobs = new ArrayList<Job>();
for (com.softlayer.api.service.network.media.transcode.Account account : accounts) {
  log.debug("Transcode account: " + account.getAccountId());
  log.debug("Transcode jobs count: " + account.getTranscodeJobCount());
      
  jobs.addAll(account.getTranscodeJobs());
}
log.debug("Jobs count: " + jobs.size());
```

And here is the produced output

```
11:00:49.500 [main] DEBUG i.wintech.wcm.cwfa.cdn.TranscodeImpl - Transcode account: 452421
11:00:49.500 [main] DEBUG i.wintech.wcm.cwfa.cdn.TranscodeImpl - Transcode jobs count: null
11:00:49.500 [main] DEBUG i.wintech.wcm.cwfa.cdn.TranscodeImpl - Jobs count: 0
```

Only one account is found, which I guess its right, but no jobs are shown.

On the SoftLayer portal page I can see the several jobs that I have been able to create, either through the portal itself or other API calls.

What am I doing wrong? Does the API call that I am using only returns active jobs? Eventually, how can I list completed transcoding jobs?

**Comment by raulcabero** [comment]
Hello,

To get the jobs please use this method: http://sldn.softlayer.com/reference/services/SoftLayer_Network_Media_Transcode_Account/getTranscodeJobs

here an example:

```
import com.google.gson.Gson;
import com.softlayer.api.ApiClient;
import com.softlayer.api.RestApiClient;
import com.softlayer.api.service.network.media.transcode.Account;

public class GetTranscodeJobs {

	public static void main(String[] args) {
		String user = "set me";
		String apikey = "set me";

		Long transcodeId = new Long(1514);

		// Declare the API client
		ApiClient client = new RestApiClient().withCredentials(user, apikey);
		Account.Service transcodeService = Account.service(client, transcodeId);

		// Get the transcode jobs
		try {
			Gson gson = new Gson();
			System.out.println(gson.toJson(transcodeService.getTranscodeJobs()));

		} catch (Exception e) {
			System.out.println("Unable to retrieve the jobs. "
					+ e.getMessage());
		}
	}
}

```

If you have more questions about Softlayer API you can post your questions here https://forums.softlayer.com/forum

I hope it helps

Regards

**Comment by cretz** [comment]
@riso - Also, for the record, the getters you call are only for already present data. If not using object masks, you will have to call service methods to get the data as the entire data graph isn't populated by default.

**Comment by riso** [comment]
Thank you for your answers. 

It still not clear to me what `transcodeId` should represent, a transcode job ID? Does it mean that in order to list jobs I have to create one first and keep track of its id?

Either way I tried passing a random number, a valid (completed) transcode Job ID and the ID of my transcode account (452421) but I always got the following exception:

```
com.softlayer.api.ApiException$NotFound: Unable to find object with id of 'XXX'.(code: SoftLayer_Exception_ObjectNotFound, status: 404)
```

**Comment by raulcabero** [comment]
Hello,

The "transcodeid" is the id of the SoftLayer_Network_Media_Transcode_Account object associated to your account , you can get that id by calling the SoftLayer_Account::getTranscodeAccounts method (for more information see http://sldn.softlayer.com/reference/services/SoftLayer_Account/getTranscodeAccounts)

I reviewed your code and it seems you are printing the id of your account (452421) and not the id of the the SoftLayer_Network_Media_Transcode_Account object (please review this page for more information http://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Media_Transcode_Account)

You need to print the "id" instead "accountID" and use that id to list the jobs

Regards

**Comment by cretz** [comment]
Closing as answered since it has been idle for a week.
