### ISSUE TITLE
Relational property "storageType" is not visible for SoftLayer_Account::getNetworkStorage method

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-java#28]
I am trying to get information about "storageType" relational property, but this property is not available to be used in object mask for method SoftLayer_Account::getNetworkStorage.

```java
        Account.Service accountService = Account.service(client);
        // Declare an object mask, to get relational properties
        accountService.withMask().networkStorage().storageType();
```

The above code is not working, However, I can retrieve that property using a Rest request:

```
https://$user:$apiKey@api.softlayer.com/rest/v3/SoftLayer_Account/getNetworkStorage?objectMask=mask[storageType]

Method: Get
```

**Comment by camporter** [comment]
Could you provide more information about how the code is not working? Is there an API error, or incorrect results, or is the storageType() method not defined when creating the mask? I tested masking the storage type and it works here. Maybe try regenerating API classes?

**Comment by rubercuellar** [comment]
I'm attaching an image

![1-18-2016 9-36-32 am](https://cloud.githubusercontent.com/assets/10092234/12392703/480e3cb0-bdc7-11e5-8c78-9514e3184f69.png)

**Comment by camporter** [comment]
Yeah, try generating the API classes again, which should resolve the issue.

**Comment by camporter** [comment]
I haven't seen an update, so I'm closing this. Please reopen if there is still an issue.
