### ISSUE TITLE
SoftLayer_Network_Service_Vpn_Overrides::createObjects is not exposed

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-java#31]
It is not possible to create VPN Overrides, I tried the following code:

``` java
import com.softlayer.api.ApiClient;
import com.softlayer.api.RestApiClient;
import com.softlayer.api.service.Account;
import com.softlayer.api.service.network.Subnet;
import com.softlayer.api.service.network.service.vpn.Overrides;
import com.softlayer.api.service.user.Customer;

Overrides.Service overrideService = Overrides.service(client);
List<Overrides> overrides = new ArrayList<Overrides>();

Overrides objectOverride1 = new Overrides();    
objectOverride1.setUserId(539047l);
objectOverride1.setSubnetId(112382l);
overrides.add(objectOverride1);

boolean result = overrideService.createObjects(overrides);
System.out.println("Have been set the overrides successfully? " + result);
```

The following exception is displayed:

`"error":"Function (\"createObject\") is not a valid method for this service.","code":"SoftLayer_Exception_Public"}`

**Comment by camporter** [comment]
A new version of the client has been released (0.2.4). Updating to this newer version should get you the newest updates to the API.

Please update this issue if updating to 0.2.4 solves your issue.

**Comment by camporter** [comment]
It looks like the API needs an update to support createObject, which is why this request is failing. Closing as this is not an issue with the java client specifically.

**Comment by allmightyspiff** [comment]
createObjects does exist though https://softlayer.github.io/reference/services/SoftLayer_Network_Service_Vpn_Overrides/createObjects/

just for reference.
