### ISSUE TITLE
SoftLayer_Network_Monitor service is not exposed

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-java#32]
I'm trying to use these methods:

getIpAddressesByHardware
getIpAddressByVirtualGuest

from 

[SoftLayer_Network_Monitor](http://sldn.softlayer.com/reference/services/SoftLayer_Network_Monitor) service and I cannot instantiate the service.

**Comment by camporter** [comment]
I tried the following code without any issue (use a hardware or virtual guest object of your own):

```java
Monitor.Service monitorService = Monitor.service(client);
List<IpAddress> ipList = monitorService.getIpAddressesByHardware(hardware, "");
for (IpAddress ip : ipList) {
    System.out.println(ip.getId() + ", " + ip.getIpAddress());
}
```

Could you provide more detail?

**Comment by rubercuellar** [comment]
I'm really sorry, you are right, my mistake
