### ISSUE TITLE
It's not possible to set init parameters for SoftLayer_Hardware_Server service

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-java#33]
I tried the following code:

```java

import com.softlayer.api.service.hardware.Server;
...
        // Define the hardware
        Long hardwareId = new Long(92862);

        // Create client
        ApiClient client = new RestApiClient().withCredentials(username, apiKey);

        // Define SoftLayer_Hardware_Server service
        Server.Service serverService = Server.service(client, hardwareId);
```

I was not able to set init parameters

**Comment by camporter** [comment]
This is a duplicate of https://github.com/softlayer/softlayer-java/issues/21. Please try the latest master and compile the sources via maven again. You'll then have the correct service type in the example given.

**Comment by rubercuellar** [comment]
My apologies, I tried with the latest master and it works fine. Thanks a lot.
