### ISSUE TITLE
Virtual_Guest::setUserMetadata and Virtual_Guest::getUserData are not exposed

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-java#35]
The following methods are not available using SoftLayer API Java Client:

[SoftLayer_Virtual_Guest::setUserMetadata](http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/setUserMetadata)
[SoftLayer_Virtual_Guest::getUserData](http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/getUserData)

These methods are working fine for SoftLayer_Hardware_Server service but not for SoftLayer_Virtual_Guest.

**Comment by camporter** [comment]
On master with freshly generated services, `setUserMetadata` and `getUserData` are available on `Guest.Service` for me. Do you have a specific example?

**Comment by rubercuellar** [comment]
Not a bug, I was able to use the methods (master branch)
