### ISSUE TITLE
[Create Object] Can i specify the vlan?

### ISSUE THREAD

**Issue by DurdenP** [softlayer/softlayer-java#41]
When i create a new server, can i specify the "vlan"?
I'll explain. 
I noticed that when i create the first machine in a datacenter are automatically create two vlans.
Eg, if i create a server in "dal05", are created:
- bcr01a.dal05 (private vlan, max 64 ip)
- fcr01a.dal05 (public vlan, max 16 ip)

The instance will be inserted in these vlans.
I wonder: in a datacenter, there could be two or more vlans?
Or rather, can i have in the datacenter named "dal05" two or more couple (bcr/fcr) of vlans?
If yes, how do i decide (when i create a server) in which of these i want to put it?

**Comment by FernandoOjeda** [comment]
- Yes, you can specify the vlan, when you are creating a new server.
e.g see the following java example how to create a virtual guest with their respective public and private vlans.

```
```
package virtual_guest.virtualGuest;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.softlayer.api.ApiClient;
import com.softlayer.api.RestApiClient;
import com.softlayer.api.service.Location;
import com.softlayer.api.service.container.product.Order;
import com.softlayer.api.service.network.Vlan;
import com.softlayer.api.service.virtual.Guest;
import com.softlayer.api.service.virtual.guest.SupplementalCreateObjectOptions;
import com.softlayer.api.service.virtual.guest.network.Component;

/**
 CreateObject.

 createObject() enables the creation of computing instances on an account. This method is a simplified alternative 
 to interacting with the ordering system directly.

 Important manual pages:
 https://softlayer.github.io/reference/services/SoftLayer_Virtual_Guest/
 https://softlayer.github.io/reference/services/SoftLayer_Virtual_Guest/createObject/

 @license <http://sldn.softlayer.com/article/License>
 @author SoftLayer Technologies, Inc. <sldn@softlayer.com>
 */

public class CreateVirtualGuest {
    public static void main(String [] arg){
        String username = "set me";
        String apiKey = "set me";

        Location location = new Location();
        location.setName("dal13");

        SupplementalCreateObjectOptions supplementalCreateObjectOptions = new SupplementalCreateObjectOptions();
        supplementalCreateObjectOptions.setFlavorKeyName("ACL1_8X60X100");

        Vlan vlan = new Vlan();
        vlan.setId(495138L);

        Vlan vlan2 = new Vlan();
        vlan2.setId(361652L);

        Component component = new Component();
        component.setNetworkVlan(vlan);

        Component component2 = new Component();
        component2.setNetworkVlan(vlan2);

        Guest guest = new Guest();
        guest.setHostname("test");
        guest.setDomain("test.local");
        guest.setDatacenter(location);
        guest.setHourlyBillingFlag(true);
        guest.setLocalDiskFlag(true);
        guest.setOperatingSystemReferenceCode("CENTOS_7_64");
        guest.setSupplementalCreateObjectOptions(supplementalCreateObjectOptions);
        guest.setPrimaryNetworkComponent(component);
        guest.setPrimaryBackendNetworkComponent(component2);

        ApiClient client = new RestApiClient().withCredentials(username, apiKey).withLoggingEnabled();
        Guest.Service guestService = Guest.service(client);

        try {
            // Try to create a new Standard Ticket
            Order result = guestService.generateOrderTemplate(guest);
            // Print response in JSON format
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            System.out.println(gson.toJson(result));
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
}

```  

```
- When you create a new server without adding vlans, the system searches a public (frontend) and private (backend) vlans available in the datacenter selected and add them to the server by default to be connected to the respective router.
- Yes, in the datacenter can be two or more vlans
- When you create a new network vlan you can select what type of vlan will be public or private.
- If you have created public and private vlans in your account you can select them to create your server and the system will not add vlans by default. With the option bellow you can add private(backend interface of the computing instance) and public(frontend interface of the computing instance) vlan for you server.

guest.setPrimaryNetworkComponent(component); // public network vlan (frontend)
guest.setPrimaryBackendNetworkComponent(component2); // private network vlan (backend)

these two options are above in the code example.

Reference:
https://softlayer.github.io/reference/services/SoftLayer_Virtual_Guest/createObject/
https://softlayer.github.io/reference/datatypes/SoftLayer_Container_Product_Order_Network_Vlan/

**Comment by camporter** [comment]
Closing as there hasn't been any updates and a solution has been provided.
