### ISSUE TITLE
The container SoftLayer_Container_Product_Order_Network_Storage_AsAService is not avaialable

### ISSUE THREAD

**Issue by raulcabero** [softlayer/softlayer-java#43]
In order to order Block storages as a service, it is needed to use the container "SoftLayer_Container_Product_Order_Network_Storage_AsAService" currently this container is not available using the Java Client so the block storage as service cannot be ordered.

**Comment by camporter** [comment]
A new version of the client has been released (0.2.4). It should roll out to the central repository today. Updating to this newer version should get you the newest updates to the API.
 
Please update this issue if updating to 0.2.4 solves your issue.

**Comment by camporter** [comment]
Going ahead and closing as there hasn't been an update.
