### ISSUE TITLE
com.softlayer.api.service.network.Storage should have provisionedIops property

### ISSUE THREAD

**Issue by jwakemanBM** [softlayer/softlayer-java#45]
The client does not allow for this REST method:  https://sldn.softlayer.com/reference/services/softlayer_network_storage/getprovisionediops

**Comment by jwakemanBM** [comment]
I am a business partner with IBM developing a plugin for IBM Cloud APM. My boss's manager at IBM instructed us to use this library for the product with the understanding that the library was being maintained. Is this not the case?

**Comment by camporter** [comment]
A new version of the client has been released (0.2.4). It should roll out to the central repository today. Updating to this newer version should get you the newest updates to the API.
 
Please update this issue if updating to 0.2.4 solves your issue.

**Comment by jwakemanBM** [comment]
Thanks so much for the quick resolution! It looks like the travis build failed, was the artifact manually uploaded to maven central?
