### ISSUE TITLE
Unable to submit multiple guest objects by using createObjects API

### ISSUE THREAD

**Issue by malyadrinaidu** [softlayer/softlayer-java#47]
what I can see in the logs is that the client is not calling the method "createObjects" in the requests there is not any method request when the API sees this it tries to call the createObject method by default:

Running POST on https://api.softlayer.com/rest/v3.1/SoftLayer_Virtual_Guest.json with body: {"parameters":[[{"complexType":"SoftLayer_Virtual_Guest","maxMemory":1024,"hostname":"rcaberodeleteme","domain":"test.com","hourlyBillingFlag":true,"startCpus":1,"operatingSystemReferenceCode":"UBUNTU_LATEST","localDiskFlag":false,"datacenter":{"complexType":"SoftLayer_Location","name":"che01"}}]]}
Got 500 on https://api.softlayer.com/rest/v3.1/SoftLayer_Virtual_Guest.json with body: {"error":"The property 'hostname' must be set to create an instance of 'SoftLayer_Virtual_Guest'.","code":"SoftLayer_Exception_MissingCreationProperty"}

**Comment by camporter** [comment]
This is a known issue. I will have a change in to work around this by explicitly using the createObjects method.
