### ISSUE TITLE
Support for the new services ReservedCapacityGroup and PlacementGroup

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-java#59]
The current version 0.2.5 doesn't support the new services like ReservedCapacityGroup and PlacementGroup

**Comment by allmightyspiff** [comment]
I think you just have to run `mvn generate-sources` to rebuild the supported services, I don't think this is something that requires a code update. Can you check?

**Comment by acamacho82** [comment]
Yeah, I cloned the repository and those services are in my local repository after running `mvn generate-sources`, and with `mvn package` they are into a `*.jar` file.

There are users which set this client as a dependency in their own maven projects so I think it would be better if a new version is released and uploaded in the maven central repositories.

https://mvnrepository.com/artifact/com.softlayer.api/softlayer-api-client
http://central.maven.org/maven2/com/softlayer/api/softlayer-api-client/

**Comment by camporter** [comment]
I'll do a new release with the latest services.

**Comment by camporter** [comment]
Version 0.2.6 has been released, with the latest service and type updates.
