### ISSUE TITLE
Account.Service does not implement toString 

### ISSUE THREAD

**Issue by nebulorum** [softlayer/softlayer-java#9]
I was trying to use the Java API using Scala. The code works fine with one exception: when you use the REPL, Account.Service does not implement toString. So commands like the following do not work on the REPL:

      val service = Account.service(client)

Since the it will print out the value of the command that was just executed. You can work around this with the ```:silent``` options. 

But it would be nice to have the ability to print out the object while you are exploring. When using the ```:silent``` option something like: 

     scala> :silent
     scala> val service = Account.service(client)
     // Worked :)
     scala> service.toString
     java.lang.RuntimeException: Unrecognized method: public java.lang.String java.lang.Object.toString()

I know most of the code is created dynamically. I was wondering is some toString could be added to the generated code?

**Comment by cretz** [comment]
Ah, yes I can do that. I have even been contemplating a set of Scala macros to make consuming this easier (but doing type providers becomes a bit difficult).

In fact, I will proxy all java.lang.Object methods to the lower level. You'll note this might happen w/ equals, hashCode, etc.

**Comment by nebulorum** [comment]
I haven't played much, but so far the API is working fine from Scala. I did not find a way to clear object masks. But if that is a missing feature I'll open another issue.

**Comment by cretz** [comment]
True, that is not a feature we added because we were expecting services to be created on need instead of reused a lot, but we should support it. I have opened #10 to track it
